# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-05 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0018_smslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='IImioAesHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Identifier')),
                ('description', models.TextField(verbose_name='Description')),
                ('server_url', models.CharField(help_text='SERVER URL', max_length=128, verbose_name='SERVER URL')),
                ('username', models.CharField(blank=True, max_length=128, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='Password')),
                ('database_name', models.CharField(max_length=128, verbose_name='Database name')),
                ('users', models.ManyToManyField(blank=True, related_name='_iimioaeshealth_users_+', related_query_name='+', to='base.ApiUser')),
            ],
            options={
                'verbose_name': 'i-ImioAesHealth',
            },
        ),
    ]
